version: '3.8'

services:
  petmonitor:
    build: .
    #ports:
    #  - "5000:5000"
    network_mode: "host"
    volumes:
      - ./src:/app/src
      - ./model.h5:/models/model.h5
      - ./images:/images:rw
      - ./logs:/logs:rw
      - ./database:/database:rw
    command: sh -c "cd /app/src; python3 app.py"
